language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-21
    - android-22
    - android-25

    # Additional components
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25

jdk: oraclejdk8
#
# before_install:
#     - rm -rf ~/.linuxbrew
#     - yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
#     - export PATH="$HOME/.linuxbrew/bin:$PATH"
#     - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
#     - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
#     - brew install jdk
#     - export JAVA_HOME=/home/travis/.linuxbrew/Cellar/jdk/1.8.0_77
